import programming from './assest/image/prog.jpg'
const FakeData =[
{
id: 1,
 image:'programming',
 name:"durjoy Talukdar Nayim",
 jobTitle:'full stack developer',
 jobDetails:'next topper',
 location: 'banani,dhaka',
 jobType: 'Remote',
 salary:'nagatiablo',
 skill: 'required skill',
 node:'node js',
 react:'react',
 next: 'next js',
 express:'express',
 docor:'docor',
 mongo:'mongo',
 detail:'understanding react useEffect cleanUp function',
 title:'programming',
 descreption:'javascript zero to hero', 
 category:'online',
 liveClass:"40 + live class",
 price:'BDT 5000/-'
},
{id:2,
 image:'https://i.imgur.com/ow4yr0t.png',
 title:'programming',
 name:"durjoy Talukdar Nayim",
 jobTitle:'full stack developer',
 jobDetails:'next topper',
 location: 'banani,dhaka',
 jobType: 'Remote',
 salary:'nagatiablo',
 skill: 'required skill',
 node:'node js',
 react:'react',
 next: 'next js',
 express:'express',
 docor:'docor',
 mongo:'mongo',
 detail:'understanding react useEffect cleanUp function',
 descreption:'javascript zero to hero', 
 category:'online',
 liveClass:"40 + live class",
 price:'BDT 5000/-'
},

{id:3,
image:'https://i.imgur.com/ow4yr0t.png',
 title:'programming',
 name:"durjoy Talukdar Nayim",
 jobTitle:'full stack developer',
 jobDetails:'next topper',
 location: 'banani,dhaka',
 jobType: 'Remote',
 salary:'nagatiablo',
 skill: 'required skill',
 node:'node js',
 react:'react',
 next: 'next js',
 express:'express',
 docor:'docor',
 mongo:'mongo',
 detail:'understanding react useEffect cleanUp function',
 descreption:'javascript zero to hero', 
 category:'online',
 liveClass:"40 + live class",
 price:'BDT 5000/-'
},
{id:4,
 image:'https://i.imgur.com/ow4yr0t.png',
 title:'programming',
 name:"durjoy Talukdar Nayim",
 jobTitle:'full stack developer',
 jobDetails:'next topper',
 location: 'banani,dhaka',
 jobType: 'Remote',
 salary:'nagatiablo',
 skill: 'required skill',
 node:'node js',
 react:'react',
 next: 'next js',
 express:'express',
 docor:'docor',
 mongo:'mongo',
 detail:'understanding react useEffect cleanUp function',
 descreption:'javascript zero to hero', 
 category:'online',
 liveClass:"40 + live class",
 price:'BDT 5000/-'
},
{id:5,
 image:'https://i.imgur.com/ow4yr0t.png',
 title:'programming',
 name:"durjoy Talukdar Nayim",
 jobTitle:'full stack developer',
 jobDetails:'next topper',
 location: 'banani,dhaka',
 jobType: 'Remote',
 salary:'nagatiablo',
 skill: 'required skill',
 node:'node js',
 react:'react',
 next: 'next js',
 express:'express',
 docor:'docor',
 mongo:'mongo',
 detail:'understanding react useEffect cleanUp function',
 descreption:'javascript zero to hero', 
 category:'online',
 liveClass:"40 + live class",
 price:'BDT 5000/-'
},

{id:6,
image:'https://i.imgur.com/ow4yr0t.png',
 title:'programming',
 name:"durjoy Talukdar Nayim",
 jobTitle:'full stack developer',
 jobDetails:'next topper',
 location: 'banani,dhaka',
 jobType: 'Remote',
 salary:'nagatiablo',
 skill: 'required skill',
 node:'node js',
 react:'react',
 next: 'next js',
 express:'express',
 docor:'docor',
 mongo:'mongo',
 detail:'understanding react useEffect cleanUp function',
 descreption:'javascript zero to hero', 
 category:'online',
 liveClass:"40 + live class",
 price:'BDT 5000/-'
},

]
export default FakeData